- name: Installation of prometheus
  apt:
    name:
      - prometheus
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: Add Elasticsearch APT repository key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  when: ansible_distribution == "Ubuntu"

- name: Add Elasticsearch APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update APT cache
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Start Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"


- name: Install Kibana
  apt:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Start and enable Kibana service
  service:
    name: kibana
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"


- name: Install Logstash
  apt:
    name: logstash
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Start and enable Logstash service
  service:
    name: logstash
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"
